### ISSUE TITLE
OS X Port

### ISSUE THREAD

**Issue by CodaFi** [CodaFi/CFIFrostedOverlayView#4]
Control should be nearly identical, though NSView might not want any part in this

**Comment by fabianofrancesconi** [comment]
FYI OS X supports [backgroundfilters property](http://developer.apple.com/library/ios/#DOCUMENTATION/GraphicsImaging/Reference/CALayer_class/Introduction/Introduction.html#//apple_ref/occ/instp/CALayer/backgroundFilters)

This should help without using GPUImage. Moreover, for this kind of tasks, using GPUImage is quite an overkill.

**Comment by CodaFi** [comment]
@elbryan Good point.  There's still some caveats that have to get enumerated if we were to use background filters (namely, NSWindow will have a conniption if this is set as its `contentView`).

**Comment by CodaFi** [comment]
For all interested, see c24121917eca480d01f0d8e11ff65b981b03c4e1
