### ISSUE TITLE
Getting white view in simulator, but demo project works

### ISSUE THREAD

**Issue by justinamberson** [CodaFi/CFIFrostedOverlayView#6]
Hello, great control, can't wait til I can get it figured out. I built the demo project for the simulator and it works fine. I went ahead and added the project files to a custom project, and when I try to add the blur on my view I just get a white rectangle.  

I'm wondering if it's because I'm not giving it enough time to render before displaying it.  Your sample code in the ReadMe has the view being added to the superview before the viewToBlur property gets set. However, you also say this:

"Because of the way that this control renders its superview, you must provide it an offset if you choose to not have the control take up the entirety of its superview, and guarantee that it is not onscreen when its superview is being rendered."

Should I instead be changing the viewToBlur property before I add to the superview? I also wonder if I should be rendering the frosted view as early as possible, because right now I do it instantly on a button touch. (I have a scroll view with a changing background that would affect the actual image that gets overlaid...no way to know the content offset inside the scrollview until the user touches the button)

**Comment by justinamberson** [comment]
I can't seem to edit my post but I want to also mention that if I drag the simulator behind another window and then pull it back out, about a quarter of the frosted glass effect gets rendered.

**Comment by PasqualePuzio** [comment]
Any update on this ? I'm having the same issue

**Comment by CodaFi** [comment]
@PasqualePuzio I do not recommend you use this project anymore, as I have neither the time nor the energy to keep it up to date.

**Comment by PasqualePuzio** [comment]
Hi,

Got it. Please mark the project as "not maintained" or "broken" so that people know it's not a good idea to use it.

Thanks

Inviato da iPhone

**Comment by CodaFi** [comment]
@PasqualePuzio Done.  If you wish to take up maintenance of the project, or have any further issues, please open another issue.  I'd be willing to fork over the rights to this to anybody willing to spend the time and effort I can't.
